--11:50 29/1/2023 
--Las l-ineas en blanco son detectadas por SQLplus como
--el inicio de un nuevo comando. Por lo tanto, -estas
--se deben borrar.
--------------------
--(Act.)23:11 21/6/2023
--Luego de crear la base  de datos, se  debe crear
--de manera autom-atica el respaldo (backup) y
--el escript para luego volver a recuperar sin
--inconvenientes en caso de requerirlo.
---------------------
DROP TABLE CONDUCTOR CASCADE CONSTRAINTS;
CREATE TABLE CONDUCTOR(
 CEDULA VARCHAR(10) NOT NULL PRIMARY KEY, 
 NOMBRE VARCHAR(50) NULL,
 TELEFONO VARCHAR(15),
 DIRECCION VARCHAR(20),
 SALARIO DECIMAL(8,2),
 CIUDAD VARCHAR(15)
);

DROP TABLE CAMION CASCADE CONSTRAINTS;
CREATE TABLE CAMION(
 PLACA VARCHAR(10) NOT NULL PRIMARY KEY,
 MODELO VARCHAR(15) NULL,
 TIPO VARCHAR(15),
 POTENCIA VARCHAR(10)
);

DROP TABLE CONDUCE CASCADE CONSTRAINTS;
CREATE TABLE CONDUCE(
 CEDULA_CONDUCTOR VARCHAR(10),
 PLACA_CAMION VARCHAR(10),
 FECHA DATE,
 ----
 FOREIGN KEY(CEDULA_CONDUCTOR) REFERENCES
  CONDUCTOR(CEDULA),
 FOREIGN KEY(PLACA_CAMION) REFERENCES
  CAMION (PLACA), 
 ----
 PRIMARY KEY(CEDULA_CONDUCTOR, PLACA_CAMION, FECHA)
);
--Para que no existan registros repetidos, se forma una Clave Primaria Compuesta.


DROP TABLE PROVINCIA CASCADE CONSTRAINTS;
CREATE TABLE PROVINCIA(
 COD_PROVINCIA VARCHAR(10) PRIMARY KEY,
 NOMBRE VARCHAR(15)
);

DROP TABLE PAQUETE;
CREATE TABLE PAQUETE(
 COD_PAQUETE VARCHAR(10) PRIMARY KEY,
 DESCRIPCION VARCHAR(30),
 DESTINATARIO VARCHAR(50),
 DIRECCION_DESTINATARIO VARCHAR(20),
 CEDULA_CONDUCTOR VARCHAR(10),
 PROVINCIA_DESTINO VARCHAR(10), 
 --En el campo "PROVINCIA_DESTINO" se ingresa el "C-odigo de provincia"
 ----
 FOREIGN KEY(CEDULA_CONDUCTOR) REFERENCES
  CONDUCTOR(CEDULA),
 FOREIGN KEY(PROVINCIA_DESTINO) REFERENCES
  PROVINCIA(COD_PROVINCIA)
);


--INSERCI-ON O INGRESO DE DATOS---
INSERT INTO CONDUCTOR
 VALUES('123456789', 'JUAN PEREZ', '4598498',
 'CALLE N-20', 900000, 'QUITO');

INSERT INTO CAMION
 VALUES('FK-1010', 'HINO FC 1021', '2DB', '70,13');
--Potencia en Cavallos de Vapor.

INSERT INTO CONDUCE
 VALUES('123456789', 'FK-1010', '16/06/2023');

INSERT INTO PROVINCIA
 VALUES('8080','PICHINCHA');

INSERT INTO PAQUETE
 VALUES('53434', 'CARTON CON MEDICINA NATURAL', 'JAVIER SANDOVAL', 
 'CALLE S/N 9', '123456789', '8080');

--Mostrar tablas
SELECT * FROM CONDUCTOR;
SELECT * FROM CAMION;
SELECT * FROM CONDUCE;
SELECT * FROM PROVINCIA;
SELECT * FROM PAQUETE;

-----AL FINAL DE LA PR-ACTICA, SE RECOMIENDA BORRAR TODO---
DROP TABLE CONDUCTOR CASCADE CONSTRAINTS;
DROP TABLE CAMION CASCADE CONSTRAINTS;
DROP TABLE CONDUCE CASCADE CONSTRAINTS;
DROP TABLE PROVINCIA CASCADE CONSTRAINTS;
DROP TABLE PAQUETE;

